#!/bin/sh
#
# Automatically add branch name to every commit message except merge commit.

COMMIT_EDITMSG=$1

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //')
  printf "# $NAME\n\n$(cat $COMMIT_EDITMSG)" >| $COMMIT_EDITMSG
}

MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchName
fi
